[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
escrow = "EcWG8mVNom4wmqWxXZSshhA2Udark9tt5ebZ6xSCbgAR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/phantom-keypair.json"

[scripts]
test = "../node_modules/.bin/jest --preset ts-jest"
